// ---------------------------------------------------------------- //
// This file is autogenerated by pioasm version 2.3.0; do not edit! //
// ---------------------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

#ifdef __cpp_constexpr
#define __pio_const constexpr
#else
#define __pio_const const
#endif

// ------ //
// ps2out //
// ------ //

#define ps2out_wrap_target 0
#define ps2out_wrap 31
#define ps2out_pio_version 0

static __pio_const uint16_t ps2out_program_instructions[] = {
            //     .wrap_target
    0xe180, //  0: set    pindirs, 0             [1]
    0xd050, //  1: irq    clear 0 rel     side 0
    0x00d4, //  2: jmp    pin, 20
    0xc010, //  3: irq    nowait 0 rel
    0x20a1, //  4: wait   1 pin, 1
    0x4001, //  5: in     pins, 1
    0xa026, //  6: mov    x, isr
    0xa0c3, //  7: mov    isr, null
    0x002a, //  8: jmp    !x, 10
    0x0000, //  9: jmp    0
    0xe728, // 10: set    x, 8                   [7]
    0xe781, // 11: set    pindirs, 1             [7]
    0xe780, // 12: set    pindirs, 0             [7]
    0x4601, // 13: in     pins, 1                [6]
    0xe681, // 14: set    pindirs, 1             [6]
    0x064c, // 15: jmp    x--, 12                [6]
    0xe780, // 16: set    pindirs, 0             [7]
    0xbe42, // 17: nop                    side 1 [6]
    0xe781, // 18: set    pindirs, 1             [7]
    0x0500, // 19: jmp    0                      [5]
    0x00f6, // 20: jmp    !osre, 22
    0x0002, // 21: jmp    2
    0xc010, // 22: irq    nowait 0 rel
    0xe02a, // 23: set    x, 10
    0xe580, // 24: set    pindirs, 0             [5]
    0x00dd, // 25: jmp    pin, 29
    0x6060, // 26: out    null, 32
    0xc034, // 27: irq    wait 4 rel
    0x0000, // 28: jmp    0
    0x6581, // 29: out    pindirs, 1             [5]
    0xe581, // 30: set    pindirs, 1             [5]
    0x0558, // 31: jmp    x--, 24                [5]
            //     .wrap
};

#if !PICO_NO_HARDWARE
static __pio_const struct pio_program ps2out_program = {
    .instructions = ps2out_program_instructions,
    .length = 32,
    .origin = -1,
    // NOTE (hand-edit, not pioasm output): the .pio_version field emitted by newer
    // pioasm (2.3.x) is omitted here. QMK bundles an older Pico SDK whose
    // `struct pio_program` has no such member (cf. col_*_pio.pio.h), and omitting it
    // zero-inits to 0 (= RP2040 / PIO v0) on newer SDKs too. .used_gpio_ranges stays
    // guarded by PICO_PIO_VERSION (0 on RP2040), so it compiles on both.
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config ps2out_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + ps2out_wrap_target, offset + ps2out_wrap);
    sm_config_set_sideset(&c, 2, true, true);
    return c;
}

  void ps2out_program_init(PIO pio, uint sm, uint offset, uint dat, uint clk) {
    pio_sm_config c = ps2out_program_get_default_config(offset);
    pio_gpio_init(pio, clk);
    pio_gpio_init(pio, dat);
    // Use a frequency high enough to effectivly sample clock and data.
    sm_config_set_clkdiv(&c, 320); // 2.5 µs
    sm_config_set_jmp_pin(&c, clk);
    sm_config_set_set_pins(&c, clk, 1);
    sm_config_set_sideset_pins(&c, dat);
    sm_config_set_out_pins(&c, dat, 1);
    sm_config_set_out_shift(&c, true, true, 11);
    sm_config_set_in_pins(&c, dat);
    sm_config_set_in_shift(&c, true, true, 9);
    pio_sm_init(pio, sm, offset, &c);
    pio_sm_set_enabled(pio, sm, true);
  }

#endif

