#pragma once

#define DYNAMIC_KEYMAP_LAYER_COUNT 3

#define VIAL_KEYBOARD_UID {0x5B, 0x18, 0xFB, 0x3C, 0xFB, 0x0D, 0xE4, 0xE4}
#define VIAL_UNLOCK_COMBO_ROWS {0, 1}
#define VIAL_UNLOCK_COMBO_COLS {0, 1}

