#pragma once

#define DYNAMIC_KEYMAP_LAYER_COUNT 3

#define VIAL_KEYBOARD_UID {0x8A, 0x15, 0xC1, 0x84, 0x70, 0x3D, 0xA5, 0xBC}
#define VIAL_UNLOCK_COMBO_ROWS {0, 0}
#define VIAL_UNLOCK_COMBO_COLS {0, 0}

#define BOOTMAGIC_LITE_ROW 0
#define BOOTMAGIC_LITE_COLUMN 0

#define HAPTIC_OFF_IN_LOW_POWER 1
