#pragma once

#define DYNAMIC_KEYMAP_LAYER_COUNT 3

#define VIAL_KEYBOARD_UID {0xD4, 0x5F, 0x03, 0xD2, 0xB6, 0x6B, 0xA4, 0xB1}
#define VIAL_UNLOCK_COMBO_ROWS {0, 1}
#define VIAL_UNLOCK_COMBO_COLS {0, 1}

#define BOOTMAGIC_LITE_ROW 0
#define BOOTMAGIC_LITE_COLUMN 0
